services:
  app:
    build:
      context: .
      target: frankenphp_dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/app
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    tty: true
